"""Remove complainant fields from complaints table

Revision ID: 04a3409771d0
Revises: 8975e4d55aea
Create Date: 2025-10-10 02:03:32.943796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04a3409771d0'
down_revision: Union[str, Sequence[str], None] = '8975e4d55aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove complainant fields from complaints table
    op.drop_column('complaints', 'complainant_phone')
    op.drop_column('complaints', 'complainant_address')
    op.drop_column('complaints', 'complainant_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back complainant fields to complaints table
    op.add_column('complaints', sa.Column('complainant_name', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('complainant_address', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('complainant_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###
