"""Add accused job, office address, email, etc fields

Revision ID: 4a5a2a26a7ac
Revises: 64e07e44e7a8
Create Date: 2025-11-14 20:14:42.324461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a5a2a26a7ac'
down_revision: Union[str, Sequence[str], None] = '64e07e44e7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Add accused job, office address, email, etc fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]

        if 'accused_office_address' not in columns:
            op.add_column('complaints', sa.Column('accused_office_address', sa.Text(), nullable=True))
        if 'accused_job' not in columns:
            op.add_column('complaints', sa.Column('accused_job', sa.String(), nullable=True))
        if 'accused_email' not in columns:
            op.add_column('complaints', sa.Column('accused_email', sa.String(), nullable=True))
        if 'accused_etc' not in columns:
            op.add_column('complaints', sa.Column('accused_etc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]

        if 'accused_etc' in columns:
            op.drop_column('complaints', 'accused_etc')
        if 'accused_email' in columns:
            op.drop_column('complaints', 'accused_email')
        if 'accused_job' in columns:
            op.drop_column('complaints', 'accused_job')
        if 'accused_office_address' in columns:
            op.drop_column('complaints', 'accused_office_address')
    # ### end Alembic commands ###
