"""Add complainant office address and phone fields

Revision ID: 554abfca9570
Revises: b6fb7c82cc4e
Create Date: 2025-11-14 20:05:42.124217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '554abfca9570'
down_revision: Union[str, Sequence[str], None] = 'b6fb7c82cc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('accused_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('accused_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accused_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crime_fact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('complaint_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('incident_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('has_evidence', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('duplicate_complaint', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('related_criminal_case', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('related_civil_case', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('generated_complaint_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('s3_conversation_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ai_session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('complainant_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('complainant_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('complainant_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('complaints_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('complaints_pkey'))
    )
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    # ### end Alembic commands ###
