"""Add complainant office address and phone fields

Revision ID: 554abfca9570
Revises: b6fb7c82cc4e
Create Date: 2025-11-14 20:05:42.124217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '554abfca9570'
down_revision: Union[str, Sequence[str], None] = 'b6fb7c82cc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Add complainant office address and phone fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]

        if 'complainant_office_address' not in columns:
            op.add_column('complaints', sa.Column('complainant_office_address', sa.Text(), nullable=True))
        if 'complainant_home_phone' not in columns:
            op.add_column('complaints', sa.Column('complainant_home_phone', sa.String(), nullable=True))
        if 'complainant_office_phone' not in columns:
            op.add_column('complaints', sa.Column('complainant_office_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]

        if 'complainant_office_phone' in columns:
            op.drop_column('complaints', 'complainant_office_phone')
        if 'complainant_home_phone' in columns:
            op.drop_column('complaints', 'complainant_home_phone')
        if 'complainant_office_address' in columns:
            op.drop_column('complaints', 'complainant_office_address')
    # ### end Alembic commands ###
