"""Add complainant job field

Revision ID: 64e07e44e7a8
Revises: 554abfca9570
Create Date: 2025-11-14 20:09:17.424244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64e07e44e7a8'
down_revision: Union[str, Sequence[str], None] = '554abfca9570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Add complainant job field."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]

        if 'complainant_job' not in columns:
            op.add_column('complaints', sa.Column('complainant_job', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]

        if 'complainant_job' in columns:
            op.drop_column('complaints', 'complainant_job')
    # ### end Alembic commands ###
