"""Add temp_complainant_info table

Revision ID: 8975e4d55aea
Revises: c21bb1592f4e
Create Date: 2025-10-10 01:53:34.100931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8975e4d55aea'
down_revision: Union[str, Sequence[str], None] = 'c21bb1592f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create temp_complainant_info table
    op.create_table(
        'temp_complainant_info',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('complainant_name', sa.String(), nullable=False),
        sa.Column('complainant_address', sa.Text(), nullable=False),
        sa.Column('complainant_phone', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_complainant_info_id'), 'temp_complainant_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop temp_complainant_info table
    op.drop_index(op.f('ix_temp_complainant_info_id'), table_name='temp_complainant_info')
    op.drop_table('temp_complainant_info')
    # ### end Alembic commands ###
