"""Initial migration with users table including address

Revision ID: 9cde48243b78
Revises: 
Create Date: 2025-10-06 23:40:42.336489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cde48243b78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 먼저 nullable=True로 컬럼 추가
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    # 2. 기존 데이터에 기본값 설정
    op.execute("UPDATE users SET address = '' WHERE address IS NULL")
    # 3. nullable=False로 변경
    op.alter_column('users', 'address', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
