"""Re-add complainant fields to complaints table

Revision ID: b6fb7c82cc4e
Revises: 04a3409771d0
Create Date: 2025-10-10 02:43:52.767139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6fb7c82cc4e'
down_revision: Union[str, Sequence[str], None] = '04a3409771d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]

        # Add complainant fields back to complaints table if they don't exist
        if 'complainant_name' not in columns:
            op.add_column('complaints', sa.Column('complainant_name', sa.String(), nullable=True))
        if 'complainant_address' not in columns:
            op.add_column('complaints', sa.Column('complainant_address', sa.Text(), nullable=True))
        if 'complainant_phone' not in columns:
            op.add_column('complaints', sa.Column('complainant_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]

        # Remove complainant fields from complaints table if they exist
        if 'complainant_phone' in columns:
            op.drop_column('complaints', 'complainant_phone')
        if 'complainant_address' in columns:
            op.drop_column('complaints', 'complainant_address')
        if 'complainant_name' in columns:
            op.drop_column('complaints', 'complainant_name')
    # ### end Alembic commands ###
