"""Re-add complainant fields to complaints table

Revision ID: b6fb7c82cc4e
Revises: 04a3409771d0
Create Date: 2025-10-10 02:43:52.767139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6fb7c82cc4e'
down_revision: Union[str, Sequence[str], None] = '04a3409771d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add complainant fields back to complaints table
    op.add_column('complaints', sa.Column('complainant_name', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('complainant_address', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('complainant_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove complainant fields from complaints table
    op.drop_column('complaints', 'complainant_phone')
    op.drop_column('complaints', 'complainant_address')
    op.drop_column('complaints', 'complainant_name')
    # ### end Alembic commands ###
