"""Add phone_number to users and complainant fields to complaints

Revision ID: c21bb1592f4e
Revises: dbcd4109ebcd
Create Date: 2025-10-10 00:55:11.763248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c21bb1592f4e'
down_revision: Union[str, Sequence[str], None] = 'dbcd4109ebcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add phone_number to users table
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))

    # Add complainant fields to complaints table
    op.add_column('complaints', sa.Column('complainant_name', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('complainant_address', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('complainant_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove complainant fields from complaints table
    op.drop_column('complaints', 'complainant_phone')
    op.drop_column('complaints', 'complainant_address')
    op.drop_column('complaints', 'complainant_name')

    # Remove phone_number from users table
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
