"""Add phone_number to users and complainant fields to complaints

Revision ID: c21bb1592f4e
Revises: dbcd4109ebcd
Create Date: 2025-10-10 00:55:11.763248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c21bb1592f4e'
down_revision: Union[str, Sequence[str], None] = 'dbcd4109ebcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Add phone_number to users table
    if 'users' in inspector.get_table_names():
        user_columns = [col['name'] for col in inspector.get_columns('users')]
        if 'phone_number' not in user_columns:
            op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))

    # Add complainant fields to complaints table
    if 'complaints' in inspector.get_table_names():
        complaint_columns = [col['name'] for col in inspector.get_columns('complaints')]

        if 'complainant_name' not in complaint_columns:
            op.add_column('complaints', sa.Column('complainant_name', sa.String(), nullable=True))
        if 'complainant_address' not in complaint_columns:
            op.add_column('complaints', sa.Column('complainant_address', sa.Text(), nullable=True))
        if 'complainant_phone' not in complaint_columns:
            op.add_column('complaints', sa.Column('complainant_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Remove complainant fields from complaints table
    if 'complaints' in inspector.get_table_names():
        complaint_columns = [col['name'] for col in inspector.get_columns('complaints')]

        if 'complainant_phone' in complaint_columns:
            op.drop_column('complaints', 'complainant_phone')
        if 'complainant_address' in complaint_columns:
            op.drop_column('complaints', 'complainant_address')
        if 'complainant_name' in complaint_columns:
            op.drop_column('complaints', 'complainant_name')

    # Remove phone_number from users table
    if 'users' in inspector.get_table_names():
        user_columns = [col['name'] for col in inspector.get_columns('users')]
        if 'phone_number' in user_columns:
            op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
