"""add police_station_name to complaints

Revision ID: eda74b57f2cd
Revises: 1deb40424c61
Create Date: 2025-12-01 01:58:27.182785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda74b57f2cd'
down_revision: Union[str, Sequence[str], None] = '1deb40424c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]
        if 'police_station_name' not in columns:
            # police_stations 테이블은 유지 - 삭제하지 않음
            op.add_column('complaints', sa.Column('police_station_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'complaints' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('complaints')]
        if 'police_station_name' in columns:
            op.drop_column('complaints', 'police_station_name')
    # ### end Alembic commands ###
