"""Add downloaded_at field to Complaint model

Revision ID: f56e0a1e53f6
Revises: 9c9065091d5c
Create Date: 2025-11-29 05:39:01.823518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56e0a1e53f6'
down_revision: Union[str, Sequence[str], None] = '9c9065091d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'downloaded_at')
    # ### end Alembic commands ###
